### ISSUE TITLE
Miss-remark: v⊗u being different from u⊗v is implied not by v!=u, only by linear independence

### ISSUE THREAD

**Issue by code-hunger** [winitzki/linear-algebra-book#2]
Hello again! 2 years later I think I caught another mistake :laughing: 

The first remark in section 2.2.1 reads

> A tensor v1 ⊗ v2 ∈ V ⊗ V is not equal to the tensor v2 ⊗ v1 if v1 != v2.

I spent quite some time proving it (I even "succeeded"!) and then trying to find my mistake, it was a fun exercise.

I knew I was wrong because a simple counterexample is given by any non-zero `v1` and `v2=0`. Then `0 = v1 ⊗ v2 = v2 ⊗ v1` while `v1 != v2`.

Anyway, the truth turned out to be that the mentioned equality implies v1 and v2 are not equal but **linearly dependent**: https://math.stackexchange.com/questions/3883395/u-otimes-v-u-otimes-v-leftrightarrow-u-lambda-u-textrm-and-v-la

**Comment by winitzki** [comment]
Thank you! This is right. I will fix the text.

**Comment by winitzki** [comment]
I updated the text in `version-1.3-print`.
